MVC_DEMO2/MVC_DEMO2/Controllers/AccountCustomController.cs
using DEMO.DAL.Models;
using MVC_DEMO2.Helpers;
using MVC_DEMO2.Models;
using MVC_DEMO2.Models.Log;
using MVC_DEMO2.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MVC_DEMO2.Controllers
{
    public class AccountCustomController : Controller
    {
        private WebClientHelper _webClient;
        public AccountCustomController()
        {
            _webClient = new WebClientHelper(); 
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            UserMasterVM model = new UserMasterVM
            {
                UserEmail = "khacluong@gmail.com",
                Password = "P@ssword00"
            };
            return View(model);
        }

        //[HttpPost]
        //[AllowAnonymous]
        //public ActionResult Login(UserMasterVM model, string returnUrl)
        //{
        //    try
        //    {
        //        if (!ModelState.IsValid)
        //        {
        //            return View(model);
        //        }

        //        var result = VerifyUserNamePassword(model);
        //        if (result)
        //        {
        //            HttpContext.Session["UserInfo"] = model;
        //            //HttpContext.Session.Timeout = 30;
        //            FormsAuthentication.SetAuthCookie(model.UserEmail, true);
        //            return RedirectToAction("Index", "Students", new { area = "Students" });
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "Invalid username or password");
        //        }
        //        ViewBag.ReturnUrl = returnUrl;
        //        return View(model);
        //    }
        //    catch (ExceptionCustom ex)
        //    {
        //        var errorMessage = string.Format("Error Code {0}, Message error: {1}", ex.ErrorCode, ex.ErrorMessage);
        //        Log.Error(errorMessage, ex);
        //        ModelState.AddModelError("", ex.ErrorMessage);
        //    }
        //    return View(model);

        //}

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(UserMasterVM model, string returnUrl)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var respone = _webClient.Post(UrlAPI.LoginAPI, model);
                if(respone != null)
                {
                    HttpContext.Session["UserInfo"] = model;
                    //HttpContext.Session.Timeout = 30;
                    var result = JsonConvert.DeserializeObject<Dictionary<string, string>>(respone);
                    var token = result["data"];
                    HttpCookie ck = new HttpCookie("tokenAPI", token);
                    Response.Cookies.Add(ck);
                    FormsAuthentication.SetAuthCookie(model.UserEmail, true);
                    return RedirectToAction("Index", "Students", new { area = "Students" });
                }
                return View(model);
            }
            catch (ExceptionCustom ex)
            {
                var errorMessage = string.Format("Error Code {0}, Message error: {1}", ex.ErrorCode, ex.ErrorMessage);
                Log.Error(errorMessage, ex);
                ModelState.AddModelError("", ex.ErrorMessage);
            }
            return View(model);

        }


        [HttpGet]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private bool VerifyUserNamePassword(UserMasterVM userMasterVM)
        {
            using (SchoolContext context = new SchoolContext())
            {
                bool IsValidUser = context.UserMaster.Any(user => user.UserEmail.ToLower() ==
                     userMasterVM.UserEmail.ToLower() && user.Password == userMasterVM.Password);
                if (!IsValidUser)
                {
                    throw new ExceptionCustom(1000, string.Format("username [{0}] or password [{1}] is not correct", userMasterVM.UserEmail, userMasterVM.Password));
                }
                return IsValidUser;
            }
        }
    }
}

MVC_DEMO2/MVC_DEMO2/Views/AccountCustom/Login.cshtml
@model MVC_DEMO2.ViewModel.UserMasterVM
@{
    ViewBag.Title = "Log in";
    var model = Model;
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "AccountCustom", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.UserEmail, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.UserEmail, new { @class = "form-control", value = model.UserEmail })
                        @Html.ValidationMessageFor(m => m.UserEmail, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", value = model.Password })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}