MVC_DEMO2/MVC_DEMO2/Areas/Students/Controllers/StudentsController.cs
using MVC_DEMO2.Helpers;
using MVC_DEMO2.ViewModel;
using MVC_DEMO2.ViewModel.Model;
using MVC_DEMO2.ViewModel.SearchModel;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MVC_DEMO2.Areas.Students.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private WebClientHelper ClientHelper
        {
            get
            {
                var token = Request.Cookies.Get("tokenAPI").Value;
                return new WebClientHelper(token);
            }
        }
        public StudentsController()
        {

        }

        public ActionResult Index()
        {
            var messError = TempData["MessageError"] as string;
            if (messError != null)
            {
                ModelState.AddModelError(string.Empty, messError);
            }
            int pageSize = 3;
            int pageIndex = 1;
            var response = ClientHelper.Get(UrlAPI.GetStudents);
            var modelView = new StudentViewModelMVC();
            if (response != null)
            {
                var result = JsonConvert.DeserializeObject<IEnumerable<StudentViewModel>>(response);
                modelView.ListStudentVM = result.ToPagedList(pageIndex, pageSize);
                modelView.StudentViewModel.Classes = _selectListItem;
            }
            return View(modelView);
        }

        [HttpPost]
        public ActionResult Index(List<int> ids, string action)
        {
            switch (action)
            {
                case "DeleteSelected":
                    return DeleteSeleted(ids);
                default:
                    return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult SearchCondition(SearchStudentVM searchModel)
        {
            searchModel.PageIndex = searchModel.PageIndex == 0 ? 1 : searchModel.PageIndex;
            searchModel.PageSize = 3;
            var response = ClientHelper.Post(UrlAPI.GetStudentByCondition, searchModel);
            var modelView = new StudentViewModelMVC();
            if (response != null)
            {
                var result = JsonConvert.DeserializeObject<IEnumerable<StudentViewModel>>(response);
                modelView.ListStudentVM = result.ToPagedList(searchModel.PageIndex, searchModel.PageSize);
                modelView.SearchStudentVM = searchModel;
            }
            return PartialView("_PartialViewSearchStudent", modelView);
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var param = new Dictionary<string, string>() { { "id", id.ToString() } };
            var response = ClientHelper.Get(UrlAPI.GetStudentsById, param);
            var studentVM = new StudentViewModel();
            if (response != null)
            {
                studentVM = JsonConvert.DeserializeObject<StudentViewModel>(response);
                studentVM.Classes = _selectListItem;
                if (studentVM == null)
                {
                    return HttpNotFound();
                }
            }
            return View(studentVM);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var studentVM = new StudentViewModel
            {
                StudentCode = Guid.NewGuid().ToString(),
                Classes = _selectListItem,
            };
            return PartialView(studentVM);
        }

        [HttpPost]
        public ActionResult Create(StudentViewModel studentvm)
        {
            studentvm.Classes = _selectListItem;
            if (ModelState.IsValid)
            {
                var response = ClientHelper.Post(UrlAPI.CreateStudent, studentvm);
                if (response != null)
                {
                    var result = JsonConvert.DeserializeObject<StudentViewModel>(response);
                }
                ViewBag.MessageSuccess = String.Format("Create student {0} {1} success", studentvm.LastName, studentvm.FirstMidName);
                return PartialView("_PartialStudent", new StudentViewModel
                {
                    StudentCode = Guid.NewGuid().ToString(),
                    Classes = _selectListItem
                });
            }
            return PartialView("_PartialStudent", studentvm);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //get student
            var param = new Dictionary<string, string>() { { "id", id.ToString() } };
            var response = ClientHelper.Get(UrlAPI.GetStudentsById, param);
            var studentVM = new StudentViewModel();
            if (response != null)
            {
                studentVM = JsonConvert.DeserializeObject<StudentViewModel>(response);
                studentVM.Classes = _selectListItem;
                if (studentVM == null)
                {
                    return HttpNotFound();
                }
            }
            return PartialView("_PartialStudent", studentVM);
        }

        [HttpPost]
        public ActionResult Edit(StudentViewModel studentVM)
        {
            studentVM.Classes = _selectListItem;
            if (ModelState.IsValid)
            {
                var response = ClientHelper.Post(UrlAPI.UpdateStudent, studentVM);
                if (response != null)
                {
                    ViewBag.MessageSuccess = "Update Sucess";

                    return PartialView("_PartialStudent", studentVM);
                }
            }
            return PartialView("_PartialStudent", studentVM);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var param = new Dictionary<string, string>() { { "id", id.ToString() } };
            var response = ClientHelper.Get(UrlAPI.GetStudentsById, param);
            var studentVM = new StudentViewModel();
            if (response != null)
            {
                studentVM = JsonConvert.DeserializeObject<StudentViewModel>(response);
                if (studentVM == null)
                {
                    return HttpNotFound();
                }
            }
            return View(studentVM);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var param = new Dictionary<string, string>() { { "id", id.ToString() } };
            var response = ClientHelper.Get(UrlAPI.DeleteStudent, param);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteSeleted(List<int> ids)
        {
            var response = ClientHelper.Post(UrlAPI.DeleteStudentSelected, ids);
            return RedirectToAction("Index");
        }

        private IEnumerable<SelectListItem> _selectListItem
        {
            get
            {
                var response = ClientHelper.Get(UrlAPI.GetClasses);
                if (response != null)
                {
                    var result = JsonConvert.DeserializeObject<List<ClassViewModel>>(response);
                    return result.Select(c => new SelectListItem
                    {
                        Value = c.ID.ToString(),
                        Text = c.ClassName
                    });
                }
                return Enumerable.Empty<SelectListItem>();
            }
        }
    }
}

MVC_DEMO2/MVC_DEMO2/Areas/Students/Views/Shared/_ModalCreateStudent.cshtml
@model MVC_DEMO2.ViewModel.Model.StudentViewModel

@{
    var modelStudent = Model;
}


@{
    ViewBag.Title = "Create";
}

@using (Ajax.BeginForm("Create", "Students",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "partialStudentId_create",
        OnBegin = "OnBegin",
        OnSuccess = "OnSuccess",
        OnFailure = "OnFailure",
        LoadingElementId = "progress"
    }))
{

    <div class="modal fade" id="createstudent-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title"><b>Create Student</b></h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="partialStudentId_create">
                    @Html.Partial("_PartialStudent", modelStudent)
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function OnBegin() {
        showloading();
    }
    function OnSuccess(response) {
        hideloading();
    }
    function OnFailure(response) {
        debugger
        alert(response);
    }

    function showloading() {
        $('#modelloading').modal('show');
    }
    function hideloading() {
        $("#modelloading").modal('hide');
    }
</script>

MVC_DEMO2/MVC_DEMO2/Areas/Students/Views/Shared/_ModalEditStudent.cshtml
@model MVC_DEMO2.ViewModel.Model.StudentViewModel

@{
    var modelStudent = Model;
}


@{
    ViewBag.Title = "Create";
}

@using (Ajax.BeginForm("Edit", "Students",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "partialStudentId_update",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "OnBegin",
        OnSuccess = "OnSuccess",
        OnFailure = "OnFailure",
        LoadingElementId = "progress"
    }))
{

    <div class="modal fade" id="editstudent-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title"><b>Edit Student</b></h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="partialStudentId_update">
                    @Html.Partial("_PartialStudent", modelStudent)
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function OnBegin() {
        showloading();
    }
    function OnSuccess(response) {
        hideloading();
    }
    function OnFailure(response) {
        debugger
        alert(response);
    }

    function showloading() {
        $('#modelloading').modal('show');
    }
    function hideloading() {
        $("#modelloading").modal('hide');
    }
</script>

MVC_DEMO2/MVC_DEMO2/Areas/Students/Views/Shared/_PartialStudent.cshtml
@model MVC_DEMO2.ViewModel.Model.StudentViewModel

@{
    ViewBag.Title = "Create";
}
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    @if (!string.IsNullOrEmpty(ViewBag.MessageSuccess))
    {
        <div class="text-success"> @ViewBag.MessageSuccess</div>
    }
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" hidden>
        @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StudentCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentCode, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
            @Html.ValidationMessageFor(model => model.StudentCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClassId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ClassId, new SelectList(Model.Classes, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "Class" })
            @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

MVC_DEMO2/MVC_DEMO2/Areas/Students/Views/Shared/_PartialViewSearchStudent.cshtml
@using PagedList.Mvc
@model MVC_DEMO2.ViewModel.StudentViewModelMVC

@{
    var listStudentVM = Model.ListStudentVM;
    var modelSeach = Model.SearchStudentVM;
}
<div id="partialLoadData">
    @using (Html.BeginForm())
    {
        <p>
            <button type="button" class="btn btn-primary" onclick="processModal()">Create</button> |
            <button type="submit" class="btn btn-danger" name="action" value="DeleteSelected" onclick="return confirm('Are you sure you wish to delete selected Student?')">Delete Selected</button>
        </p>

        <table class="table">
            <tr>
                <th>
                    <input type="checkbox" id="checkall" value="">
                </th>
                <th>
                    StudentCode
                </th>
                <th>
                    LastName
                </th>
                <th>
                    FirstMidName
                </th>
                <th>
                    EnrollmentDate
                </th>
                <th></th>
            </tr>

            @foreach (var student in listStudentVM)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="ids" value="@student.ID" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => student.StudentCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => student.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => student.FirstMidName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => student.EnrollmentDate)
                    </td>
                    <td>
                        <input type="button" class="btn btn-primary" onclick="editStudent(@student.ID)" value="E">
                        <input type="button" class="btn btn-success" value="O">
                        <input type="button" class="btn btn-danger" value="X">
                    </td>
                </tr>
            }
        </table>
    }
    Page @(listStudentVM.PageCount < listStudentVM.PageNumber ? 0 : listStudentVM.PageNumber) / @listStudentVM.PageCount
    @Html.PagedListPager(listStudentVM, page => Url.Action("Index", new { page = page }))
</div>

<script type="text/javascript">
    function processModal() {
        debugger
        $("#createstudent-modal").modal("show");
    }

    function editStudent(id) {
        debugger
        //call ajax prepare form id
        var url = "https://localhost:44347/StudentsArea/Students/Edit?id=" + id;
        $.get(url, function () {
        }).done(function (data) {
            $("#partialStudentId_update").html(data);
            $("#editstudent-modal").modal("show");
        })
            .fail(function () {
                alert("error");
            })
    }
</script>